### ISSUE TITLE
Native Image of Micronaut-spring 3.0.0 spring boot example run failed with "java.util.zip.ZipException: zip END header not found"

### ISSUE THREAD

**Issue by qianyiyong** [micronaut-projects/micronaut-spring#142]
Thanks for reporting an issue, please review the task list below before submitting the
issue. Your issue report will be closed if the issue is incomplete and the below tasks not completed.

NOTE: If you are unsure about something and the issue is more of a question a better place to ask questions is on Stack Overflow (https://stackoverflow.com/tags/micronaut) or Gitter (https://gitter.im/micronautfw/). DO NOT use the issue tracker to ask questions.

### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Follow the "https://github.com/micronaut-projects/micronaut-spring/tree/v3.0.0/examples/greeting-service", use gradlew assemble build a jar, named "greeting-service-0.1.0.jar"
![image](https://user-images.githubusercontent.com/51293069/101591340-4f176180-3a27-11eb-9856-438c13f30c24.png)

2. Install GraalVM & NativeImage, the version as follows: 
D:\Code\self\micronaut\micronaut-spring\examples\greeting-service\build\libs>java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06, mixed mode, sharing)

D:\Code\self\micronaut\micronaut-spring\examples\greeting-service\build\libs>native-image --version
GraalVM Version 20.3.0 (Java Version 11.0.9+10-jvmci-20.3-b06)

3. Build Native Image successfully
D:\Code\self\micronaut\micronaut-spring\examples\greeting-service\build\libs>native-image --no-fallback -cp greeting-service-0.1.0.jar org.springframework.boot.loader.JarLauncher
[org.springframework.boot.loader.jarlauncher:1392]    classlist:     895.58 ms,  0.96 GB
[org.springframework.boot.loader.jarlauncher:1392]        (cap):   1,469.37 ms,  0.96 GB
[org.springframework.boot.loader.jarlauncher:1392]        setup:   2,667.71 ms,  0.96 GB
[org.springframework.boot.loader.jarlauncher:1392]     (clinit):     271.55 ms,  2.29 GB
[org.springframework.boot.loader.jarlauncher:1392]   (typeflow):   7,974.15 ms,  2.29 GB
[org.springframework.boot.loader.jarlauncher:1392]    (objects):   8,374.35 ms,  2.29 GB
[org.springframework.boot.loader.jarlauncher:1392]   (features):     257.57 ms,  2.29 GB
[org.springframework.boot.loader.jarlauncher:1392]     analysis:  17,142.97 ms,  2.29 GB
[org.springframework.boot.loader.jarlauncher:1392]     universe:     398.50 ms,  2.29 GB
[org.springframework.boot.loader.jarlauncher:1392]      (parse):   1,036.94 ms,  2.29 GB
[org.springframework.boot.loader.jarlauncher:1392]     (inline):   1,156.33 ms,  2.30 GB
[org.springframework.boot.loader.jarlauncher:1392]    (compile):   7,723.41 ms,  4.75 GB
[org.springframework.boot.loader.jarlauncher:1392]      compile:  10,609.65 ms,  4.75 GB
[org.springframework.boot.loader.jarlauncher:1392]        image:   1,466.48 ms,  4.75 GB
[org.springframework.boot.loader.jarlauncher:1392]        write:     415.26 ms,  4.75 GB
[org.springframework.boot.loader.jarlauncher:1392]      [total]:  33,708.75 ms,  4.75 GB

A .exe file named org.springframework.boot.loader.jarlauncher.exe created:
D:\Code\self\micronaut\micronaut-spring\examples\greeting-service\build\libs>
![image](https://user-images.githubusercontent.com/51293069/101591660-fb594800-3a27-11eb-8f4a-73bf4af273bc.png)

4. run exe file failed. 
D:\Code\self\micronaut\micronaut-spring\examples\greeting-service\build\libs>org.springframework.boot.loader.jarlauncher.exe
Exception in thread "main" java.lang.IllegalStateException: java.util.zip.ZipException: zip END header not found
        at org.springframework.boot.loader.ExecutableArchiveLauncher.<init>(ExecutableArchiveLauncher.java:42)
        at org.springframework.boot.loader.JarLauncher.<init>(JarLauncher.java:36)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.util.zip.ZipException: zip END header not found
        at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1567)
        at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1462)
        at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1469)
        at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274)
        at java.util.zip.ZipFile$Source.get(ZipFile.java:1237)
        at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
        at java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
        at java.util.zip.ZipFile.<init>(ZipFile.java:247)
        at java.util.zip.ZipFile.<init>(ZipFile.java:177)
        at java.util.jar.JarFile.<init>(JarFile.java:348)
        at java.util.jar.JarFile.<init>(JarFile.java:319)
        at java.util.jar.JarFile.<init>(JarFile.java:285)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:119)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:114)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:100)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:91)
        at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:61)
        at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:57)
        at org.springframework.boot.loader.Launcher.createArchive(Launcher.java:127)
        at org.springframework.boot.loader.ExecutableArchiveLauncher.<init>(ExecutableArchiveLauncher.java:39)
        ... 2 more

### Expected Behaviour
run exe file successfully!

Tell us what should happen
run exe file successfully!

### Actual Behaviour
run exe file failed!

Tell us what happens instead

### Environment Information
- **Operating System**:  Windows 10 with Windows 10 SDK & x64 Native Tools Command Prompt for VS 2019
- **Micronaut Version**:  micronaut-spring 3.0.0
- **JDK Version**: 
D:\Code\self\micronaut\micronaut-spring\examples\greeting-service\build\libs>java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06, mixed mode, sharing)

D:\Code\self\micronaut\micronaut-spring\examples\greeting-service\build\libs>native-image --version
GraalVM Version 20.3.0 (Java Version 11.0.9+10-jvmci-20.3-b06)

### Example Application
![image](https://user-images.githubusercontent.com/51293069/101592011-863a4280-3a28-11eb-9726-aeaa9fa4acd5.png)

- [ ]

**Comment by qianyiyong** [comment]
@graemerocher

**Comment by qianyiyong** [comment]
need package with maven-shade-plugin, embedded jar will cause these problem
