### ISSUE TITLE
NPE in MicronautBeanFactory.getBeanDefinition

### ISSUE THREAD

**Issue by arixmkii** [micronaut-projects/micronaut-spring#156]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided (link to the problematic code line provided)
- [ ] Example that reproduces the problem uploaded to Github 
- [x] Full description of the issue provided (see below)

https://github.com/micronaut-projects/micronaut-spring/blob/master/spring-context/src/main/java/io/micronaut/spring/context/factory/MicronautBeanFactory.java#L669

This should have null check
```java
        if (definition != null && definition.isEnabled(beanContext)) {
```

Here are the implementation details from cxf library, where it expects to get specific checked exception and doesn't handle other exceptions https://github.com/apache/cxf/blob/master/core/src/main/java/org/apache/cxf/configuration/spring/ConfigurerImpl.java#L177

If I build SNAPSHOT with mentioned changes and use it instead, everything works as expected, but would be nice to have it backported at least for 3.0.X releases.

### Steps to Reproduce

1. Grails applications (starting from 4.1.0.M3) with grails-cxf plugin will fail to start, because of the unhandled exception during startup.

### Expected Behaviour

`NoSuchBeanDefinitionException` should be thrown (checked exceptions).

### Actual Behaviour

NPE is thrown.

### Environment Information

- **Operating System**: MacOS 11.1
- **Micronaut Version:** 3.0 (spring-context)
- **JDK Version:** adopopenjdk hs 11.0.9

### Example Application

Any Grails application with grails-cxf plugin

**Comment by arixmkii** [comment]
@puneetbehl FYI. You might want to bump the dependency version before releasing Grails 4.1.0 final.
